import i18nConfig from '@/i18nConfig';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import { dir } from 'i18next';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Provider from '@/lib/utils/reactQueryClient';
import DarkModeProviders from '@/lib/utils/darkModeProviders';
import TranslationsProvider from '@/components/TranslationsProvider';
import initTranslations from '../i18n';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Elmarma ',
  description: 'Generated by Enas sello'
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}
async function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const i18nNamespaces = ['home'];

  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={dir(locale)} suppressHydrationWarning>
      <body
        className={cn(' bg-background font-sans antialiased', inter.variable)}>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}>
          <Provider>
            <DarkModeProviders>
              <Navbar />
              <div className="max-w-[1100px] my-0 mx-auto">
                <div className="min-h-screen  bg-mainWhite text-mainDark">
                  {children}
                </div>
                <Footer />
              </div>
            </DarkModeProviders>
          </Provider>
        </TranslationsProvider>
      </body>
    </html>
  );
}

export default RootLayout;
